(() => {
  const data=window.TravelData||JSON.parse(document.getElementById('travel-data').textContent),plan=data.journey.plan,$=id=>document.getElementById(id);
  window.TravelData=data;let scene='journey',selected=null;
  Archify.view={fitAll(){},state:()=>({scale:1})};
  function visible(){return data.places.filter(p=>p.views[scene]);}
  function select(id){if(!visible().some(p=>p.id===id))return;selected=id;write();window.dispatchEvent(new CustomEvent('archify:travel-select',{detail:{id}}));}
  function write(){const url=new URL(location.href);if(window.TravelPackages)url.searchParams.set('destination',TravelPackages.group);url.hash='scene='+scene+(selected?'&place='+selected:'');history.replaceState(null,'',url);}
  function changeScene(next,id=null){scene=data.scenes[next]?next:'journey';selected=null;const day=scene==='journey'?0:Number(scene.slice(4));$('day').value=String(day);for(const p of data.places){p.scene=p.views[scene]?scene:'unselected';p.point=p.views[scene]||p.views.journey;}$('title').textContent=plan.title;$('map-level').textContent=day?'第 '+day+' 天 · 独立方块':'全部行程 · 真实地理位置';$('disney-open').hidden=true;document.querySelectorAll('#trip-days button').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.day)===day)));renderSchedule(day);write();window.dispatchEvent(new Event('archify:travel-change'));if(id)select(id);}
  Archify.travel={scene:()=>scene,selected:()=>selected,visible:()=>visible().map(p=>p.id),changeScene,select};
  const panel=document.createElement('section');panel.className='trip-panel';panel.innerHTML='<form id="trip-form"><label for="trip-prompt">告诉宿主 Agent，你想怎样旅行</label><textarea id="trip-prompt" rows="2"></textarea><div class="trip-form-row"><button type="submit">复制给 Agent</button></div><p id="trip-status" role="status">由宿主 LLM 生成；网页不调用模型。</p></form><div id="trip-plan"><div class="trip-plan-title"><strong></strong></div><div id="trip-days" class="trip-days"></div><p class="trip-assumption">地标为统一风格示意；箭头表示游览顺序。</p><p id="trip-calendar">开放与预约请按出行日期核对。</p><div id="trip-schedule"></div><p class="trip-route-note"></p><button id="trip-download">下载行程数据</button></div>';
  $('intro').after(panel);$('trip-prompt').value=plan.prompt;panel.querySelector('strong').textContent=plan.title;document.querySelector('.scope').hidden=true;
  $('day').replaceChildren();for(const d of [{day:0,title:'全部行程'},...plan.days]){const option=document.createElement('option');option.value=d.day;option.textContent=d.day?'第 '+d.day+' 天':d.title;$('day').append(option);const b=document.createElement('button');b.type='button';b.dataset.day=d.day;b.textContent=option.textContent;b.onclick=()=>{changeScene(d.day?'day-'+d.day:'journey');Archify.travel3d?.focusDay(d.day);};$('trip-days').append(b);}
  $('day').onchange=()=>changeScene(Number($('day').value)?'day-'+$('day').value:'journey');
  $('trip-form').onsubmit=async e=>{e.preventDefault();const prompt='使用本项目的 Archify Travel 宿主流程：'+$('trip-prompt').value+'。读取 labs/travel/HOST.md，生成并校验 journey JSON，运行 render-journey.mjs，交付流程图和总览/单日 3D 沙盘。';try{await navigator.clipboard.writeText(prompt);$('trip-status').textContent='已复制。粘贴到当前宿主 Agent 对话即可生成。';}catch{$('trip-status').textContent='请将上面的旅行需求发送给宿主 Agent，并让它按 labs/travel/HOST.md 生成。';}};
  function renderSchedule(day){$('trip-schedule').replaceChildren();for(const d of plan.days.filter(d=>!day||d.day===day)){const h=document.createElement('h3');h.textContent='第 '+d.day+' 天 · '+d.title;$('trip-schedule').append(h);for(const s of d.stops){const p=data.places.find(p=>p.id===s.id),b=document.createElement('button');b.className='schedule-stop';b.textContent=s.time+' '+p.name+' · '+s.duration;b.onclick=()=>{changeScene(d.scene,p.id);document.getElementById('mode-3d').click();};$('trip-schedule').append(b);if(s.note){const note=document.createElement('p');note.textContent=s.note;$('trip-schedule').append(note);}const href=plan.official[p.placeId];if(href){const a=document.createElement('a');a.href=href;a.textContent='官方信息 ↗';a.target='_blank';a.rel='noopener noreferrer';$('trip-schedule').append(a);}}}}
  $('trip-download').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(plan,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='journey.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  $('sources-toggle').textContent='坐标与地图来源 ↗';$('sources-toggle').onclick=()=>{$('sources').hidden=!$('sources').hidden;};$('sources').replaceChildren();const text=document.createElement('p');text.textContent='© OpenStreetMap contributors（仅已提供的道路/建筑）· 高度缺失时为估算。单日底座是展示范围，并非行政边界或真实地形高程。';$('sources').append(text);const elevation=data.journey.tiles.journey.elevation;if(elevation){const credit=document.createElement('p');credit.textContent=elevation.attribution+' · 总览为低分辨率采样，高差夸张 '+elevation.exaggeration.toFixed(1)+'×，非测绘地形。';$('sources').append(credit);}for(const p of data.places){const a=document.createElement('a');a.href=p.source;a.textContent=p.name+' · 坐标来源 ';a.target='_blank';a.rel='noopener noreferrer';$('sources').append(a);}
  const restore=()=>{const h=new URLSearchParams(location.hash.slice(1));changeScene(h.get('scene'),h.get('place'));};window.addEventListener('hashchange',restore);restore();
})();
